### ISSUE TITLE
Errors in tests

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/serapeum#64] opened 2020-07-05 09:55 UTC
I have a bunch of LOCAL macroexpansion errors when running the tests:

```lisp
 Running test suite INTERNAL-DEFINITIONS
  Running test INTERNAL-DEFINITIONS ............
  Running test LET-OVER-DEF ..
  Running test LET-OVER-DEF-VS-HOISTING .
  Running test SYMBOL-MACROLET-SCOPE .
  Running test SYMBOL-MACRO-BEFORE-MACRO .
  Running test EXPR-ENV .
  Running test REDEFINING-FUNCTIONS .
; in: LAMBDA ()
;     (SERAPEUM:LOCAL
;       (SETQ SERAPEUM.TESTS::X (SERAPEUM.TESTS::M))
;       (DEFMACRO SERAPEUM.TESTS::M () 2)
;       SERAPEUM.TESTS::X)
; 
; caught ERROR:
;   during macroexpansion of
;   (LOCAL
;     (SETQ #)
;     (DEFMACRO M # ...)
;     ...).
;   Use *BREAK-ON-SIGNALS* to intercept.
;   
;    Macro definitions in `local' must precede other expressions.
;   Offender: M

;     (LET (SERAPEUM.TESTS::X)
;       (FLET ((SERAPEUM.TESTS::M ()
;                1))
;         (SERAPEUM:LOCAL
;           (SETQ SERAPEUM.TESTS::X #)
;           (DEFMACRO SERAPEUM.TESTS::M () 2)
;           SERAPEUM.TESTS::X)))
; 
; caught STYLE-WARNING:
;   The variable X is defined but never used.

```

**Comment by ruricolist** [comment] 2020-07-05 14:33
Is it actually affecting the outcome of the tests? The test suite on SBCL is fairly noisy because of calls to eval to test for errors in code that SBCL, being more or less clairvoyant,  refuses to even compile.

**Comment by Ambrevar** [comment] 2020-07-05 15:32
Nope:

```
 Did 832 checks.
    Pass: 832 (100%)
    Skip: 0 ( 0%)
    Fail: 0 ( 0%)
```

**Comment by ruricolist** [comment] 2020-07-06 22:41
This is working as intended, so I'm closing the issue.

**Closed by ruricolist** 2020-07-06 22:41 UTC
